#if !canImport(ObjectiveC)
import XCTest

extension ListTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ListTests = [
        ("testEmptyListConcatenation", testEmptyListConcatenation),
        ("testHeadReturnsOnlyElement", testHeadReturnsOnlyElement),
        ("testHeadThrowsOnEmptyList", testHeadThrowsOnEmptyList),
        ("testIndexOnNonEmptyList", testIndexOnNonEmptyList),
        ("testListConcatenationLefthandSideEmpty", testListConcatenationLefthandSideEmpty),
        ("testListConcatenationNeitherEmpty", testListConcatenationNeitherEmpty),
        ("testListConcatenationRighthandSideEmpty", testListConcatenationRighthandSideEmpty),
        ("testTailOnEmptyThrows", testTailOnEmptyThrows),
        ("testTailReturnsEmptyWithOneElement", testTailReturnsEmptyWithOneElement),
        ("testTailReturnsTheRestOfTheList", testTailReturnsTheRestOfTheList),
        ("testUpdatingAtLastIndex", testUpdatingAtLastIndex),
        ("testUpdatingAtZeroethIndex", testUpdatingAtZeroethIndex),
        ("testUpdatingBySubscript", testUpdatingBySubscript),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ListTests.__allTests__ListTests),
    ]
}
#endif
